name: Infra Change Deploys

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  infra-deploy:
    name: Infra Deploy
    uses: ./.github/workflows/infra-change.yaml
    secrets:
      AWS_GITHUB_ROLE_ARN: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
      ALERT_EMAIL: ${{ secrets.ALERT_EMAIL }}
    with:
      runs-on: ubuntu-latest
      tf-version: '1.14.8'
      apply: true
